apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp #works when deleted
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ubuntu
          envFrom:
            - configMapRef:
                name: app-config
